import AppKit

/// Notices images copied to the clipboard so they hang too: a screenshot
/// taken with Control held down, or with Save to set to Clipboard, or an
/// image copied from a browser or from Preview. Each one is saved as a PNG in
/// Tendedero's own folder, so on the line it behaves like any screenshot.
///
/// macOS has no notification for clipboard changes, so the change count is
/// checked a few times a second. That is one cheap call; what was copied is
/// only read once its types say it is an image.
final class ClipboardWatcher {
    static let folder: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return base.appendingPathComponent("Tendedero/Clipboard", isDirectory: true)
    }()

    /// The user's choice, kept across launches. Off until they turn it on.
    static var isEnabled: Bool {
        get { UserDefaults.standard.bool(forKey: "clipboardEnabled") }
        set { UserDefaults.standard.set(newValue, forKey: "clipboardEnabled") }
    }

    /// Image types, best first. PNG is kept as it is; the rest are converted.
    private static let imageTypes: [NSPasteboard.PasteboardType] = [
        .png, .tiff, .init("public.jpeg"), .init("public.heic"),
    ]

    /// Copies that carry a picture but are not one. Text from a spreadsheet
    /// or a document also comes as an image of itself. A file copied in
    /// Finder brings its icon, and a photo copied from the line brings its
    /// file. Password managers and other apps mark private or temporary
    /// copies, following nspasteboard.org.
    private static let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
        .string, .fileURL,
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    private let pasteboard: NSPasteboard
    private let folder: URL
    private let onNew: (URL) -> Void
    private var changeCount = 0
    private var timer: Timer?
    /// The last image saved. Some apps put the same image on the clipboard
    /// again; it hangs once, unless it has been taken down since.
    private var last: (png: Data, url: URL)?

    init(pasteboard: NSPasteboard = .general, folder: URL = ClipboardWatcher.folder,
         onNew: @escaping (URL) -> Void) {
        self.pasteboard = pasteboard
        self.folder = folder
        self.onNew = onNew
    }

    func start() {
        // Whatever was on the clipboard before is not new.
        changeCount = pasteboard.changeCount
        let timer = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in self?.check() }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func check() {
        let count = pasteboard.changeCount
        guard count != changeCount else { return }
        changeCount = count
        guard let types = pasteboard.types, Set(types).isDisjoint(with: Self.ignoredTypes),
              let type = pasteboard.availableType(from: Self.imageTypes),
              let data = pasteboard.data(forType: type) else { return }
        // Converting a large image takes a moment, so it happens off the main thread.
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            let png = type == .png ? data
                : NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:])
            guard let png else { return }
            DispatchQueue.main.async { self?.save(png) }
        }
    }

    private func save(_ png: Data) {
        if let last, last.png == png, FileManager.default.fileExists(atPath: last.url.path) { return }
        do {
            try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true)
            let url = uniqueURL(in: folder, for: Self.fileName(for: Date()))
            try png.write(to: url)
            last = (png, url)
            onNew(url)
        } catch {
            log.error("Could not save a copied image: \(error.localizedDescription, privacy: .public)")
        }
    }

    /// Named like a screenshot: "Clipboard 2026-10-07 at 15.04.12.png".
    private static func fileName(for date: Date) -> String {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyy-MM-dd"
        let day = formatter.string(from: date)
        formatter.dateFormat = "HH.mm.ss"
        let time = formatter.string(from: date)
        return L("Clipboard \(day) at \(time).png", "Portapapeles \(day) a las \(time).png")
    }
}
