import AppKit
import ImageIO
import UniformTypeIdentifiers

/// A read-only source, injected in tests so they never access the user's clipboard.
@MainActor
protocol ClipboardSource {
    var changeCount: Int { get }
    var itemTypes: [[NSPasteboard.PasteboardType]] { get }
    func data(forType type: NSPasteboard.PasteboardType, at index: Int) -> Data?
}

@MainActor
private struct SystemClipboardSource: ClipboardSource {
    // Access is lazy: constructing a disabled watcher does not read the pasteboard.
    var changeCount: Int { NSPasteboard.general.changeCount }
    var itemTypes: [[NSPasteboard.PasteboardType]] {
        (NSPasteboard.general.pasteboardItems ?? []).map(\.types)
    }
    func data(forType type: NSPasteboard.PasteboardType, at index: Int) -> Data? {
        guard let items = NSPasteboard.general.pasteboardItems, items.indices.contains(index) else { return nil }
        return items[index].data(forType: type)
    }
}

/// Optional clipboard image capture, adapted from Anubhav-Rai's Tendedero PR #1:
/// https://github.com/alejandrobujan/tendedero/pull/1 (MIT; see docs/clipboard-support.md).
/// Polling only reads PNG/TIFF image data; it never writes to the pasteboard or follows URLs.
@MainActor
final class ClipboardWatcher {
    private let source: any ClipboardSource
    private let folder: URL
    private let onImage: (URL) -> Void
    private var timer: Timer?
    private var lastCount: Int?
    private static var ownChangeCount = -1

    /// No registered default: a missing preference is false.
    static var isEnabled: Bool {
        get { UserDefaults.standard.bool(forKey: "clipboardEnabled") }
        set { UserDefaults.standard.set(newValue, forKey: "clipboardEnabled") }
    }

    static func recordOwnCopy(changeCount: Int) {
        ownChangeCount = changeCount
    }

    private static let privateTypes: Set<NSPasteboard.PasteboardType> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ].reduce(into: []) { $0.insert(NSPasteboard.PasteboardType($1)) }
    static let maximumDataBytes = 32 * 1024 * 1024
    static let maximumPixelCount = 40_000_000

    convenience init(onImage: @escaping (URL) -> Void) {
        self.init(source: SystemClipboardSource(), folder: Inbox.folder, onImage: onImage)
    }

    init(source: any ClipboardSource, folder: URL, onImage: @escaping (URL) -> Void) {
        self.source = source
        self.folder = folder
        self.onImage = onImage
    }

    func start() {
        guard timer == nil else { return }
        // Enabling or re-enabling never imports the clipboard's previous contents.
        lastCount = source.changeCount
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.check() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
        lastCount = nil
    }

    /// Internal so tests can advance a synthetic clipboard without waiting for a timer.
    func check() {
        guard timer != nil else { return }
        let count = source.changeCount
        guard count != lastCount else { return }
        lastCount = count
        guard count != Self.ownChangeCount else { return }

        let items = source.itemTypes
        // Check every item before requesting any image bytes. File copies are excluded
        // because Finder also advertises a TIFF/PNG of the file's icon.
        guard !items.contains(where: { types in
            types.contains(.fileURL) || !Self.privateTypes.isDisjoint(with: types)
        }), source.changeCount == count else { return }

        for (index, types) in items.enumerated() {
            for type in [NSPasteboard.PasteboardType.png, .tiff] where types.contains(type) {
                guard source.changeCount == count else { return }
                let data = source.data(forType: type, at: index)
                guard source.changeCount == count else { return }
                guard let data, let png = Self.validatedPNG(data, type: type) else { continue }
                // Another application can replace the clipboard while we read it.
                guard source.changeCount == count else { return }
                save(png)
                return // A clipboard screenshot is one image, even with multiple representations.
            }
        }
    }

    /// Validate format and resource bounds before decoding. PNG bytes stay unchanged;
    /// TIFF's first frame is converted to PNG using the local system image decoder.
    static func validatedPNG(_ data: Data, type: NSPasteboard.PasteboardType) -> Data? {
        guard !data.isEmpty, data.count <= maximumDataBytes,
              type == .png || type == .tiff,
              let imageSource = CGImageSourceCreateWithData(data as CFData,
                [kCGImageSourceShouldCache: false] as CFDictionary),
              CGImageSourceGetType(imageSource) as String? == (type == .png ? UTType.png.identifier : UTType.tiff.identifier),
              let properties = CGImageSourceCopyPropertiesAtIndex(imageSource, 0, nil) as? [CFString: Any],
              let width = (properties[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue,
              let height = (properties[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue,
              width > 0, height > 0, width <= maximumPixelCount / height else { return nil }

        if type == .png {
            // Decode a small thumbnail to reject a header-only or corrupt PNG.
            let options: [CFString: Any] = [
                kCGImageSourceCreateThumbnailFromImageAlways: true,
                kCGImageSourceThumbnailMaxPixelSize: 1,
                kCGImageSourceShouldCacheImmediately: true
            ]
            guard CGImageSourceCreateThumbnailAtIndex(imageSource, 0, options as CFDictionary) != nil else { return nil }
            return data
        }

        guard let image = CGImageSourceCreateImageAtIndex(imageSource, 0, nil) else { return nil }
        let result = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(result, UTType.png.identifier as CFString, 1, nil) else { return nil }
        CGImageDestinationAddImage(destination, image, nil)
        guard CGImageDestinationFinalize(destination), result.length <= maximumDataBytes else { return nil }
        return result as Data
    }

    private func save(_ data: Data) {
        let url = folder.appendingPathComponent("Clipboard \(UUID().uuidString).png")
        do {
            try FileManager.default.createDirectory(at: folder, withIntermediateDirectories: true,
                attributes: [.posixPermissions: 0o700])
            try data.write(to: url, options: .atomic)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
            onImage(url)
        } catch {
            try? FileManager.default.removeItem(at: url)
            // Avoid logging image bytes, names, paths or clipboard metadata.
            log.error("Could not save a clipboard image")
        }
    }
}
